openapi: 3.1.0
info:
  title: Notes Manager API
  version: 1.0.0
  description: API for managing markdown notes

servers:
  - url: https://semaj-noncivlizable-jayse.ngrok-free.dev
    description: Your ngrok tunnel

paths:
  /api/notes:
    get:
      operationId: listNotes
      summary: List all notes
      description: Get all notes with their metadata
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object

    post:
      operationId: createNote
      summary: Create a new note
      description: Create a note with title, content, and optional tags
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - content
              properties:
                title:
                  type: string
                  description: The title of the note
                content:
                  type: string
                  description: The content of the note
                tags:
                  type: array
                  items:
                    type: string
                  description: Optional tags
      responses:
        '201':
          description: Note created

  /api/notes/search:
    post:
      operationId: searchNotes
      summary: Search notes
      description: Search notes by query text
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - query
              properties:
                query:
                  type: string
                  description: Search query
                tags:
                  type: array
                  items:
                    type: string
                  description: Filter by tags
      responses:
        '200':
          description: Search results

  /api/notes/{id}:
    get:
      operationId: getNote
      summary: Get a note by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success

    put:
      operationId: updateNote
      summary: Update a note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                content:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        '200':
          description: Note updated

    delete:
      operationId: deleteNote
      summary: Delete a note
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Note deleted

  /api/tags:
    get:
      operationId: listTags
      summary: List all tags
      responses:
        '200':
          description: Success


